### ISSUE TITLE
Compilation fails with ESPHome 2025.10.0+ with Arduino framework

### ISSUE THREAD

**Issue by sairon** [sairon/esphome-nspanel-lovelace-ui#42]
Compilation fails with `arduino` framework because of https://github.com/esphome/esphome/commit/b8cee477fe41bef0a7d6ada0f375b7fdf31a573f: 
```
In file included from src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:2:
src/esphome/components/nspanel_lovelace/nspanel_lovelace.h:12:10: fatal error: esphome/components/uart/uart_component_esp32_arduino.h: No such file or directory
   12 | #include "esphome/components/uart/uart_component_esp32_arduino.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
`esp-idf` works without issues.
