### ISSUE TITLE
Unable to build since ESPHome 2026.2.0

### ISSUE THREAD

**Issue by Benvandamme** [sairon/esphome-nspanel-lovelace-ui#47]
Hi,

there was some redesign in the build process of esphome 2026.2.0 and since then I am unable to compile for my nspanels.

`src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:2: src/esphome/components/nspanel_lovelace/nspanel_lovelace.h:16:10: fatal error: esp_http_client.h: No such file or directory  ******************************************************************************* * Looking for esp_http_client.h dependency? Check our library registry! * * CLI  > platformio lib search "header:esp_http_client.h" * Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKesp_http_client.h * *******************************************************************************     16 | #include <esp_http_client.h>       |          ^~~~~~~~~~~~~~~~~~~ compilation terminated. *** [.pioenvs/nspanel-buegelzimmer/src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp.o] Error 1 In file included from src/esphome/components/nspanel_lovelace/nspanel_lovelace_upload.cpp:1: src/esphome/components/nspanel_lovelace/nspanel_lovelace.h:16:10: fatal error: esp_http_client.h: No such file or directory  *******************************************************************************`

Probably has something to do with this part of the changelog

"ESP32 Arduino selective compilation: Arduino libraries are now disabled by default. External components that use Arduino libraries must call cg.add_library("LibraryName", None) in their to_code() to enable them."

**Comment by randybb** [comment]
Caused by https://github.com/esphome/esphome/pull/13610

A quick workaround is just add this to your config until it is fixed in the component:
```yaml
esp32:
  framework:
    advanced:
      include_builtin_idf_components:
        - esp_http_client
```

**Comment by peetereczek** [comment]
I have added the IDF component, but my build is still failing, anything I have missed?
```
esp32:
  board: esp32dev
  framework:
    type: arduino
    advanced:
      include_builtin_idf_components:
        - esp_http_client
```

**Comment by randybb** [comment]
@peetereczek switch from arduino to esp-idf, or remove that line as esp-idf is the default framework.
